name: Build for Multiple Platforms

# Указываем, что процесс запускается при каждом push или pull request в репозиторий
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Определение матрицы для запуска процесса на нескольких платформах
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # Компиляция на Linux и Windows
        include:
          - os: ubuntu-latest
          - os: windows-latest

    steps:
      # Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v2

      # Установка зависимостей (может отличаться для разных систем)
      #  - name: Set up dependencies
      #  run: |
       #   if [[ "$RUNNER_OS" == "Linux" ]]; then
        #    sudo apt-get update && sudo apt-get install -y <your-dependencies>
        #  elif [[ "$RUNNER_OS" == "Windows" ]]; then
          #  choco install <your-windows-dependencies>

      # Выполняем сборку проекта
      - name: Build project
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            make build  # Пример для Linux
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            .\build.bat  # Пример для Windows
